// FootyQuiz — Question Bank
// 150 AFL questions across 6 categories
// 25 per category: History, Players, Records, Venues, Rules, Teams

const QUESTION_BANK = [

  // ── HISTORY (25) ──────────────────────────────────────────────────
  {cat:'History', q:'In what year was the Victorian Football League (VFL) founded?', opts:['1877','1890','1897','1905'], ans:2, explain:'The VFL was founded in 1897, breaking away from the Victorian Football Association.'},
  {cat:'History', q:'Which team won the first VFL premiership in 1897?', opts:['Essendon','Geelong','Fitzroy','Collingwood'], ans:0, explain:'Essendon won the first VFL premiership in 1897.'},
  {cat:'History', q:'In what year did the VFL rebrand as the AFL?', opts:['1987','1990','1982','1995'], ans:1, explain:'The VFL rebranded as the AFL in 1990 as the competition expanded nationally.'},
  {cat:'History', q:'Which was the first interstate team to join the VFL/AFL?', opts:['West Coast Eagles','Brisbane Bears','Adelaide Crows','Sydney Swans'], ans:3, explain:'South Melbourne relocated to Sydney in 1982, becoming the Sydney Swans — the first interstate team.'},
  {cat:'History', q:'What year did the Adelaide Crows join the AFL as an expansion team?', opts:['1990','1991','1992','1993'], ans:2, explain:'The Adelaide Crows joined the AFL in 1991 as the first team based outside Victoria and NSW.'},
  {cat:'History', q:'Which club is the oldest in the AFL, founded in 1858?', opts:['Geelong','Melbourne','Carlton','Essendon'], ans:1, explain:'Melbourne Football Club was founded in 1858, making it the oldest football club in the world.'},
  {cat:'History', q:'The Collingwood vs Carlton 1970 VFL Grand Final drew a record crowd of how many?', opts:['101,000','107,527','115,000','98,000'], ans:1, explain:'The 1970 VFL Grand Final between Collingwood and Carlton drew a record 121,696 — the largest ever.'},
  {cat:'History', q:'Which year did women\'s AFL (AFLW) first begin?', opts:['2015','2016','2017','2018'], ans:2, explain:'The AFLW competition launched in February 2017 with eight teams.'},
  {cat:'History', q:'What is the name of the trophy awarded to the AFL premiership winner?', opts:['The Shield','The Premiership Cup','The Norm Smith Medal','The AFL Trophy'], ans:1, explain:'The winning team receives the Premiership Cup, also informally called the premiership cup or flag.'},
  {cat:'History', q:'Which team has appeared in the most AFL/VFL Grand Finals?', opts:['Carlton','Essendon','Collingwood','Richmond'], ans:2, explain:'Collingwood has appeared in the most Grand Finals, with over 40 appearances.'},
  {cat:'History', q:'What year did Hawthorn win four premierships in five years?', opts:['1983-1988','1986-1991','1988-1993','1991-1996'], ans:0, explain:'Hawthorn won four premierships between 1983 and 1988, a dominant era in VFL history.'},
  {cat:'History', q:'Which club was formerly known as the Fitzroy Lions before merging?', opts:['Brisbane Lions','Gold Coast Suns','GWS Giants','Port Adelaide'], ans:0, explain:'Fitzroy merged with the Brisbane Bears in 1996 to form the Brisbane Lions.'},
  {cat:'History', q:'The "Blood Rule" in AFL refers to what?', opts:['A player must leave if bleeding','A free kick for high contact','A suspension for striking','A ban on certain tackles'], ans:0, explain:'The Blood Rule requires a player to temporarily leave the field if they are bleeding until the bleeding is controlled.'},
  {cat:'History', q:'Which year did Port Adelaide join the AFL?', opts:['1997','2000','1995','1998'], ans:0, explain:'Port Adelaide joined the AFL in 1997 after a long history in the SANFL.'},
  {cat:'History', q:'The Brownlow Medal is named after which former player?', opts:['Jack Brownlow','Charlie Brownlow','Ted Brownlow','Bill Brownlow'], ans:1, explain:'The Brownlow Medal is named after Charles "Charlie" Brownlow, a former Geelong committeeman.'},
  {cat:'History', q:'Which team won back-to-back AFL premierships in 2019 and 2020?', opts:['West Coast Eagles','Richmond Tigers','Geelong Cats','Brisbane Lions'], ans:1, explain:'Richmond won back-to-back premierships in 2019 and 2020, adding to their 2017 premiership.'},
  {cat:'History', q:'What was the original name of the Gold Coast Suns when they were proposed?', opts:['Gold Coast Football Club','Surfers Paradise Sharks','Gold Coast Demons','Carrara Suns'], ans:0, explain:'The team was officially named Gold Coast Football Club before adopting the Suns nickname.'},
  {cat:'History', q:'Which interstate rivalry game is known as the "Showdown"?', opts:['Adelaide vs Port Adelaide','Melbourne vs Collingwood','Sydney vs GWS','Brisbane vs Gold Coast'], ans:0, explain:'The Adelaide Derby between Adelaide Crows and Port Adelaide is known as the Showdown.'},
  {cat:'History', q:'What year did GWS Giants play their first AFL season?', opts:['2010','2011','2012','2013'], ans:2, explain:'The Greater Western Sydney Giants played their first AFL season in 2012.'},
  {cat:'History', q:'Which VFL club became the West Coast Eagles?', opts:['No VFL club — West Coast was an expansion team','East Perth','Claremont','Swan Districts'], ans:0, explain:'West Coast Eagles was an expansion team that joined the VFL/AFL in 1987, not based on any existing VFL club.'},
  {cat:'History', q:'The "Footy Show" was a long-running AFL TV program on which network?', opts:['ABC','Seven Network','Nine Network','Ten Network'], ans:2, explain:'The AFL Footy Show ran on the Nine Network for many years as a popular Thursday night program.'},
  {cat:'History', q:'Which club\'s nickname is "The Bombers"?', opts:['Hawthorn','Essendon','West Coast','Brisbane'], ans:1, explain:'Essendon Football Club is nicknamed The Bombers, playing in red and black.'},
  {cat:'History', q:'What year did Richmond end their 37-year premiership drought?', opts:['2015','2016','2017','2018'], ans:2, explain:'Richmond ended a 37-year premiership drought in 2017, defeating Adelaide in the Grand Final.'},
  {cat:'History', q:'Which player famously kicked the ball through his own goals in 1996 to give Footscray a win?', opts:['Scott Wynd','Paul Peos','David Rhys-Jones','Matthew Lloyd'], ans:1, explain:'Paul Peos of the Bulldogs accidentally kicked through his own goal, giving Footscray an unlikely victory.'},
  {cat:'History', q:'The Anzac Day match is traditionally played between which two clubs?', opts:['Melbourne and Collingwood','Essendon and Collingwood','Richmond and Melbourne','Carlton and Essendon'], ans:1, explain:'The Anzac Day clash between Essendon and Collingwood at the MCG is one of AFL\'s most iconic fixtures.'},

  // ── PLAYERS (25) ─────────────────────────────────────────────────
  {cat:'Players', q:'Who holds the AFL record for most career goals?', opts:['Tony Lockett','Jason Dunstall','Lance Franklin','Gary Ablett Sr'], ans:0, explain:'Tony Lockett finished his career with 1,360 goals, the all-time AFL/VFL record.'},
  {cat:'Players', q:'Which player is nicknamed "Buddy"?', opts:['Nick Riewoldt','Lance Franklin','Barry Hall','Jack Riewoldt'], ans:1, explain:'Lance "Buddy" Franklin is one of the most iconic AFL forwards of the modern era.'},
  {cat:'Players', q:'Which player won the most Brownlow Medals?', opts:['Bob Skilton','Dick Reynolds','Haydn Bunton','Ian Stewart'], ans:2, explain:'Haydn Bunton won three Brownlow Medals (1932, 1935, 1937), the most by any player.'},
  {cat:'Players', q:'Who was the first player to kick 100 goals in an AFL season in the modern era?', opts:['Jason Dunstall','Tony Lockett','Matthew Lloyd','Peter Hudson'], ans:1, explain:'Tony Lockett kicked 100 goals in the 1992 season for St Kilda, a modern-era milestone.'},
  {cat:'Players', q:'Which player is known as "The Wizard" for his goal-kicking ability?', opts:['Wayne Carey','Dustin Martin','Gary Ablett Jr','Matthew Lloyd'], ans:2, explain:'Gary Ablett Jr is often called "God" — but Matthew Lloyd was nicknamed based on accuracy. Gary Ablett Jr is widely considered the greatest player of the modern era.'},
  {cat:'Players', q:'Who won the Norm Smith Medal in the 2017 AFL Grand Final?', opts:['Trent Cotchin','Dustin Martin','Jack Riewoldt','Bachar Houli'], ans:1, explain:'Dustin Martin won the Norm Smith Medal in 2017, becoming the first player to win the Brownlow and Norm Smith in the same year.'},
  {cat:'Players', q:'Which player holds the record for most AFL games played?', opts:['Michael Tuck','Kevin Bartlett','Brent Harvey','Adam Goodes'], ans:2, explain:'Brent Harvey played 432 AFL games for North Melbourne, the all-time record.'},
  {cat:'Players', q:'Wayne Carey played most of his career at which club?', opts:['Collingwood','North Melbourne','Adelaide','Kangaroos'], ans:1, explain:'Wayne Carey, "The King", played 272 games for North Melbourne (the Kangaroos) before a brief stint at Adelaide.'},
  {cat:'Players', q:'Which player was the AFL\'s first Indigenous captain to lift the premiership cup?', opts:['Adam Goodes','Eddie Betts','Michael O\'Loughlin','Andrew McLeod'], ans:0, explain:'Adam Goodes was a trailblazer for Indigenous players in the AFL throughout his career at Sydney.'},
  {cat:'Players', q:'Who kicked the famous "torpedo" behind in the 2010 AFL Grand Final replay?', opts:['Chris Judd','Darren Millane','Cloke','Collingwood player'], ans:0, explain:'The 2010 Grand Final drew and went to a replay — one of the most dramatic in history.'},
  {cat:'Players', q:'Which player famously said "I\'m going to the footy" in a viral AFL ad?', opts:['Jason Dunstall','Ted Whitten','Bob Skilton','Kevin Bartlett'], ans:1, explain:'Ted Whitten Sr was one of the most iconic figures in VFL/AFL history and a legendary Footscray player.'},
  {cat:'Players', q:'Gary Ablett Jr played for which two AFL clubs?', opts:['Geelong and Gold Coast','Geelong and Hawthorn','Gold Coast and Brisbane','Geelong and Carlton'], ans:0, explain:'Gary Ablett Jr played for Geelong (winning two premierships) before moving to the Gold Coast Suns as a founding player.'},
  {cat:'Players', q:'Which player won back-to-back Brownlow Medals in 2019 and 2020?', opts:['Patrick Dangerfield','Lachie Neale','Dustin Martin','Marcus Bontempelli'], ans:1, explain:'Lachie Neale won back-to-back Brownlow Medals in 2019 and 2020 while playing for Brisbane Lions.'},
  {cat:'Players', q:'Who is the AFL\'s all-time leading goal kicker in finals?', opts:['Tony Lockett','Jason Dunstall','Jack Riewoldt','Matthew Lloyd'], ans:1, explain:'Jason Dunstall kicked 114 goals in finals, the all-time record for finals goal kicking.'},
  {cat:'Players', q:'Which ruckman won the Brownlow Medal in 2018?', opts:['Max Gawn','Nic Naitanui','Todd Goldstein','Tom Bellchambers'], ans:0, explain:'Max Gawn won the 2018 Brownlow Medal, becoming one of the few ruckmen to win the award.'},
  {cat:'Players', q:'Who did Patrick Dangerfield move to Geelong from in 2016?', opts:['Hawthorn','Adelaide','Port Adelaide','Collingwood'], ans:1, explain:'Patrick Dangerfield made a high-profile move from Adelaide to Geelong in 2016 and won the Brownlow Medal that same year.'},
  {cat:'Players', q:'Which player holds the record for most Norm Smith Medals?', opts:['Dustin Martin','Andrew McLeod','Norm Smith himself','Luke Hodge'], ans:1, explain:'Andrew McLeod won the Norm Smith Medal twice (1997, 1998) for Adelaide, the first player to win it in consecutive years.'},
  {cat:'Players', q:'Tom Hawkins plays as what position for Geelong?', opts:['Midfielder','Ruckman','Key forward','Defender'], ans:2, explain:'Tom Hawkins is Geelong\'s key forward and has been one of the most consistent goal kickers of the modern era.'},
  {cat:'Players', q:'Which player was suspended for the infamous "Elimination Final" punch in 2008?', opts:['Barry Hall','Nick Riewoldt','Matthew Lloyd','Steven Baker'], ans:0, explain:'Barry Hall was suspended for 7 weeks after punching Brent Staker in the 2008 Elimination Final.'},
  {cat:'Players', q:'Who was the first father-son selection with both players winning Brownlow Medals?', opts:['Gary Ablett Sr and Gary Ablett Jr','Ted Whitten and Ted Whitten Jr','Bob Skilton and Matthew Skilton','Kevin Bartlett and Mark Bartlett'], ans:0, explain:'Gary Ablett Sr won the Brownlow in 1984 and Gary Ablett Jr won it in 2009 and 2013 — the only father-son Brownlow double.'},
  {cat:'Players', q:'Which club did Nic Naitanui play his entire career at?', opts:['Fremantle','West Coast Eagles','Adelaide','GWS Giants'], ans:1, explain:'Nic Naitanui has played his entire AFL career at the West Coast Eagles, becoming one of the best ruckmen in the game.'},
  {cat:'Players', q:'Who was the AFL\'s Rising Star winner in 2021?', opts:['Jason Horne-Francis','Kysaiah Pickett','Sam Walsh','Riley Thilthorpe'], ans:1, explain:'Kysaiah Pickett of Melbourne won the AFL Rising Star award in 2021.'},
  {cat:'Players', q:'Which defender won the 2022 Brownlow Medal?', opts:['Patrick Cripps','Lachie Neale','Clayton Oliver','Charlie Curnow'], ans:0, explain:'Patrick Cripps of Carlton won the 2022 Brownlow Medal in a dominant individual performance.'},
  {cat:'Players', q:'Marcus Bontempelli captains which AFL club?', opts:['St Kilda','North Melbourne','Western Bulldogs','Footscray'], ans:2, explain:'Marcus Bontempelli has been captain of the Western Bulldogs and is widely regarded as one of the best players in the competition.'},
  {cat:'Players', q:'Which player kicked the winning goal in the 2016 AFL Grand Final for the Western Bulldogs?', opts:['Tom Boyd','Jake Stringer','Jason Johannisen','Marcus Bontempelli'], ans:2, explain:'Jason Johannisen kicked the sealing goal in the Western Bulldogs\' 2016 premiership win, their first since 1954.'},

  // ── RECORDS (25) ─────────────────────────────────────────────────
  {cat:'Records', q:'What is the highest score ever recorded in a VFL/AFL match?', opts:['Geelong 37.17 (239) in 1992','St Kilda 33.27 (225) in 1955','Richmond 35.21 (231) in 1973','Carlton 38.17 (245) in 1981'], ans:0, explain:'Geelong scored 37.17 (239) against Brisbane Bears on 9 May 1992 — the highest score in VFL/AFL history.'},
  {cat:'Records', q:'Who kicked the most goals in a single AFL/VFL season?', opts:['Jason Dunstall','Peter Hudson','Bob Pratt','Gary Ablett Sr'], ans:1, explain:'Peter Hudson kicked 150 goals in the 1971 VFL season, the all-time single-season record.'},
  {cat:'Records', q:'What is the largest winning margin in a VFL/AFL Grand Final?', opts:['96 points','119 points','108 points','87 points'], ans:1, explain:'Geelong defeated Collingwood by 119 points in the 1989 VFL Grand Final, the largest Grand Final winning margin.'},
  {cat:'Records', q:'Who holds the record for most goals in a single AFL game?', opts:['Fred Fanning','Tony Lockett','Peter Hudson','Jason Dunstall'], ans:0, explain:'Fred Fanning of Melbourne kicked 18 goals in a single VFL game in 1947, a record that still stands.'},
  {cat:'Records', q:'Which player holds the record for most career Brownlow votes?', opts:['Gary Ablett Jr','Patrick Dangerfield','Dustin Martin','Lachie Neale'], ans:0, explain:'Gary Ablett Jr accumulated the most Brownlow votes across his career, reflecting his sustained dominance.'},
  {cat:'Records', q:'What is the record attendance for an AFL Grand Final?', opts:['106,000','121,696','115,000','128,000'], ans:1, explain:'The 1970 VFL Grand Final between Carlton and Collingwood drew 121,696 people to the MCG.'},
  {cat:'Records', q:'Which team went through an entire AFL season undefeated in the home and away rounds?', opts:['Geelong 2007','Hawthorn 2008','Essendon 2000','Richmond 2017'], ans:0, explain:'Geelong went through the entire 2007 home and away season undefeated before winning the premiership.'},
  {cat:'Records', q:'Who kicked the most goals in a single AFL finals series?', opts:['Jason Dunstall','Tony Lockett','Jack Riewoldt','Peter Hudson'], ans:0, explain:'Jason Dunstall kicked 23 goals in a single finals series for Hawthorn in 1988.'},
  {cat:'Records', q:'What is the lowest score ever recorded by a team in a VFL/AFL final?', opts:['2.5 (17)','1.3 (9)','0.4 (4)','3.2 (20)'], ans:1, explain:'St Kilda scored just 1.3 (9) in the 1899 VFL Final, one of the lowest scores in a final.'},
  {cat:'Records', q:'Which team holds the record for most consecutive wins?', opts:['Essendon','Geelong','Collingwood','Carlton'], ans:1, explain:'Geelong holds the record for the most consecutive wins in AFL history.'},
  {cat:'Records', q:'How many consecutive Brownlow Medals did Haydn Bunton win?', opts:['2','3','4','He never won consecutive ones'], ans:1, explain:'Haydn Bunton won the Brownlow Medal three times: 1932, 1935, and 1937 — though not all consecutive.'},
  {cat:'Records', q:'Who has the most AFL premierships as a player?', opts:['Michael Tuck','Leigh Matthews','Dustin Martin','Robert DiPierdomenico'], ans:0, explain:'Michael Tuck won 7 VFL/AFL premierships with Hawthorn between 1983 and 1991.'},
  {cat:'Records', q:'What is the record for most goals kicked by one player in a Grand Final?', opts:['12','14','9','16'], ans:1, explain:'Jack Dyer kicked 14 goals in the 1943 VFL Grand Final for Richmond, a record that still stands.'},
  {cat:'Records', q:'Which team has the longest Grand Final winning streak?', opts:['Collingwood','Essendon','Carlton','Hawthorn'], ans:3, explain:'Hawthorn won four consecutive VFL premierships from 1988 to 1991, with key players like Tuck and Brereton.'},
  {cat:'Records', q:'The fastest goal ever recorded in AFL history was how many seconds into the game?', opts:['3 seconds','6 seconds','10 seconds','15 seconds'], ans:1, explain:'The fastest goal in AFL history was kicked approximately 6 seconds after the opening bounce.'},
  {cat:'Records', q:'Which AFL team has the longest period without winning a premiership (current)?', opts:['St Kilda','North Melbourne','Carlton','Brisbane Lions'], ans:0, explain:'St Kilda\'s only VFL/AFL premiership was in 1966, making their drought the longest of any club still active.'},
  {cat:'Records', q:'Who holds the record for most consecutive Brownlow Medal wins?', opts:['Haydn Bunton','Dick Reynolds','Bob Skilton','Gary Ablett Jr'], ans:0, explain:'Haydn Bunton won consecutive Brownlow Medals in 1932 and 1935 among his three career wins.'},
  {cat:'Records', q:'What is the record for the most goals kicked in a losing effort in a Grand Final?', opts:['8 goals','10 goals','7 goals','12 goals'], ans:1, explain:'Multiple players have kicked 10 goals in losing Grand Final efforts over the history of the VFL/AFL.'},
  {cat:'Records', q:'Which AFL season had the most total goals scored across the competition?', opts:['1995','2000','2010','2019'], ans:0, explain:'The mid-1990s saw some of the highest scoring seasons in AFL history before rule changes tightened defences.'},
  {cat:'Records', q:'Who was the youngest player to win the Brownlow Medal?', opts:['Gary Ablett Jr','Patrick Dangerfield','Dyson Heppell','Adam Goodes'], ans:1, explain:'Patrick Dangerfield won the Brownlow Medal at a relatively young age with Adelaide before moving to Geelong.'},
  {cat:'Records', q:'What is the record score in a VFL/AFL match for the losing team?', opts:['23.17 (155)','19.23 (137)','21.15 (141)','25.10 (160)'], ans:2, explain:'The losing side once scored over 140 points in a VFL match, illustrating how high-scoring the game can be.'},
  {cat:'Records', q:'Which team holds the record for the most points scored in a single quarter?', opts:['Geelong','Essendon','Carlton','Melbourne'], ans:0, explain:'Geelong has been involved in multiple record-breaking scoring quarters during their dominant eras.'},
  {cat:'Records', q:'How many goals did Jason Dunstall kick across his career?', opts:['1,013','1,254','978','1,100'], ans:0, explain:'Jason Dunstall kicked 1,254 goals in his VFL/AFL career, making him one of the all-time great goal kickers.'},
  {cat:'Records', q:'What is the record for most hit-outs by a ruckman in a single game?', opts:['70','85','93','102'], ans:2, explain:'Several dominant ruckmen have achieved over 90 hit-outs in a single game across AFL history.'},
  {cat:'Records', q:'Which year saw the highest average crowd attendance in AFL history?', opts:['2005','2010','2018','2019'], ans:3, explain:'AFL crowd attendances peaked around 2019 before the COVID-19 pandemic significantly reduced crowds in 2020-21.'},

  // ── VENUES (25) ──────────────────────────────────────────────────
  {cat:'Venues', q:'What is the capacity of the MCG?', opts:['80,000','95,000','100,024','85,000'], ans:2, explain:'The MCG has a capacity of 100,024, making it the largest stadium in Australia.'},
  {cat:'Venues', q:'Which ground is the home of the Melbourne Demons?', opts:['Marvel Stadium','MCG','GMHBA Stadium','Adelaide Oval'], ans:1, explain:'The Melbourne Demons play their home games at the MCG.'},
  {cat:'Venues', q:'What is the name of Geelong\'s home ground?', opts:['Skilled Stadium','Kardinia Park','GMHBA Stadium','Simonds Stadium'], ans:2, explain:'Geelong plays at GMHBA Stadium (formerly known as Kardinia Park and Simonds Stadium).'},
  {cat:'Venues', q:'Perth Stadium (Optus Stadium) opened in what year?', opts:['2016','2017','2018','2019'], ans:2, explain:'Optus Stadium in Perth opened in January 2018 and has a capacity of around 60,000.'},
  {cat:'Venues', q:'Which AFL ground is known as "The Gabba"?', opts:['Adelaide Oval','Docklands','Brisbane Cricket Ground','Metricon Stadium'], ans:2, explain:'The Brisbane Cricket Ground, known as the Gabba, is the home of the Brisbane Lions.'},
  {cat:'Venues', q:'Marvel Stadium in Melbourne was previously known as what?', opts:['Colonial Stadium','Telstra Dome','Etihad Stadium','All of the above'], ans:3, explain:'Marvel Stadium has had multiple naming rights sponsors: Colonial Stadium, Telstra Dome, and Etihad Stadium before Marvel.'},
  {cat:'Venues', q:'What is the home ground of the Fremantle Dockers?', opts:['Subiaco Oval','Optus Stadium','Domain Stadium','HBF Park'], ans:1, explain:'The Fremantle Dockers relocated to Optus Stadium (formerly Domain Stadium) as their primary home ground.'},
  {cat:'Venues', q:'Which stadium hosted the 2020 AFL Grand Final, the first played outside Victoria?', opts:['Adelaide Oval','The Gabba','Optus Stadium','SCG'], ans:1, explain:'The 2020 AFL Grand Final was played at the Gabba in Brisbane due to COVID-19 restrictions, the first Grand Final held outside Victoria.'},
  {cat:'Venues', q:'What is the home ground of the GWS Giants?', opts:['ANZ Stadium','Spotless Stadium','GIANTS Stadium','Engie Stadium'], ans:3, explain:'GWS Giants play at Engie Stadium (formerly known as Spotless Stadium and GIANTS Stadium) in Sydney.'},
  {cat:'Venues', q:'The Adelaide Oval underwent a major redevelopment completed in which year?', opts:['2010','2012','2014','2016'], ans:2, explain:'The Adelaide Oval redevelopment was completed in 2014, transforming it into a world-class multi-sport stadium.'},
  {cat:'Venues', q:'Metricon Stadium on the Gold Coast has what approximate capacity?', opts:['25,000','30,000','35,000','40,000'], ans:1, explain:'Metricon Stadium (now People First Stadium) has a capacity of approximately 30,000.'},
  {cat:'Venues', q:'Which venue hosted the very first AFL Grand Final?', opts:['MCG','Princes Park','Fitzroy Cricket Ground','Junction Oval'], ans:0, explain:'The MCG has hosted the majority of VFL/AFL Grand Finals throughout history.'},
  {cat:'Venues', q:'What is the home ground of the Sydney Swans?', opts:['ANZ Stadium','Olympic Park','SCG','Allianz Stadium'], ans:2, explain:'The Sydney Swans play their home games at the Sydney Cricket Ground (SCG).'},
  {cat:'Venues', q:'Kardinia Park is located in which city?', opts:['Melbourne','Geelong','Ballarat','Bendigo'], ans:1, explain:'Kardinia Park (GMHBA Stadium) is located in Geelong, Victoria, home of the Geelong Cats.'},
  {cat:'Venues', q:'Which AFL ground has the nickname "The Cattery"?', opts:['Adelaide Oval','GMHBA Stadium','Optus Stadium','Marvel Stadium'], ans:1, explain:'GMHBA Stadium in Geelong is nicknamed "The Cattery" as the home of the Geelong Cats.'},
  {cat:'Venues', q:'What is the capacity of Adelaide Oval?', opts:['45,000','50,000','53,500','58,000'], ans:2, explain:'Adelaide Oval has a capacity of approximately 53,500 following its redevelopment.'},
  {cat:'Venues', q:'The MCG stands on land in which Melbourne suburb?', opts:['South Melbourne','Richmond','East Melbourne','Fitzroy'], ans:2, explain:'The MCG is located in East Melbourne, adjacent to the CBD and Yarra Park.'},
  {cat:'Venues', q:'Which suburban ground hosted many Hawthorn home games for decades?', opts:['Glenferrie Oval','Victoria Park','Princes Park','Junction Oval'], ans:0, explain:'Glenferrie Oval in Hawthorn was the Hawks\' home ground for many decades before they moved to larger venues.'},
  {cat:'Venues', q:'What is the name of Collingwood\'s famous former home ground?', opts:['Victoria Park','Junction Oval','Princes Park','Windy Hill'], ans:0, explain:'Victoria Park in Abbotsford was Collingwood\'s home ground and is famous for its working-class atmosphere.'},
  {cat:'Venues', q:'Which venue is known as "The Shrine" in AFL circles?', opts:['Marvel Stadium','MCG','AAMI Park','Etihad Stadium'], ans:1, explain:'The MCG is reverentially referred to as "The G" and sometimes "The Shrine" of Australian sport.'},
  {cat:'Venues', q:'Princes Park is the historic home of which AFL club?', opts:['Melbourne','Carlton','St Kilda','North Melbourne'], ans:1, explain:'Princes Park (now Ikon Park) is the historic home of Carlton Football Club.'},
  {cat:'Venues', q:'Which AFL venue has a roof that can be opened or closed?', opts:['MCG','Marvel Stadium','Adelaide Oval','Optus Stadium'], ans:1, explain:'Marvel Stadium (formerly Etihad Stadium) has a retractable roof, one of only a few stadiums in Australia.'},
  {cat:'Venues', q:'The Gabba is located in which Brisbane suburb?', opts:['South Brisbane','Woolloongabba','Fortitude Valley','New Farm'], ans:1, explain:'The Gabba is located in Woolloongabba, hence its nickname "The Gabba."'},
  {cat:'Venues', q:'What year did the MCG host the Olympic Games, which influenced its redevelopment?', opts:['1948','1952','1956','1960'], ans:2, explain:'Melbourne hosted the 1956 Olympic Games, and the MCG was the main stadium, leading to significant redevelopment.'},
  {cat:'Venues', q:'Which Adelaide ground did Port Adelaide use before moving to Adelaide Oval?', opts:['Football Park','AAMI Stadium','Noarlunga Oval','Hindmarsh Stadium'], ans:0, explain:'Port Adelaide played at Football Park (AAMI Stadium) before both Adelaide clubs moved to Adelaide Oval.'},

  // ── RULES (25) ───────────────────────────────────────────────────
  {cat:'Rules', q:'How many players are on each side during an AFL game?', opts:['16','17','18','20'], ans:2, explain:'Each AFL team fields 18 players, with 4 interchange players on the bench.'},
  {cat:'Rules', q:'How many quarters are played in an AFL game?', opts:['Two halves','Three thirds','Four quarters','Five periods'], ans:2, explain:'AFL matches consist of four quarters.'},
  {cat:'Rules', q:'What does a "behind" score in AFL?', opts:['0 points','1 point','2 points','3 points'], ans:1, explain:'A behind scores 1 point — occurs when ball passes between goal post and behind post, or touches any post.'},
  {cat:'Rules', q:'How many points is a goal worth in AFL?', opts:['3','4','5','6'], ans:3, explain:'A goal in AFL is worth 6 points and is scored when the ball passes through the two tall goal posts without touching them.'},
  {cat:'Rules', q:'What is a "mark" in AFL?', opts:['A kick that goes out of bounds','Catching the ball cleanly from a kick of 15+ metres','A free kick for high contact','Touching the ball on the ground'], ans:1, explain:'A mark is awarded when a player catches the ball cleanly from a kick that travels at least 15 metres without touching the ground or another player.'},
  {cat:'Rules', q:'What is the "holding the ball" rule in AFL?', opts:['You must kick the ball within 3 seconds','A player tackled with prior opportunity must dispose of the ball correctly','You cannot hold the ball for more than 5 seconds','You must handball if tackled'], ans:1, explain:'Holding the ball is called when a player who had prior opportunity to dispose of the ball is tackled and does not correctly dispose of it.'},
  {cat:'Rules', q:'How far must a player kick the ball to be awarded a mark?', opts:['10 metres','15 metres','20 metres','25 metres'], ans:1, explain:'A player must kick the ball at least 15 metres for a teammate to take a mark.'},
  {cat:'Rules', q:'What is a "rushed behind" in AFL?', opts:['A deliberate kick through the behind posts by the defending team','When a player rushes the ball through any post','A penalty against the attacking team','An accidental behind'], ans:0, explain:'A rushed behind occurs when the defending team deliberately sends the ball through their own behind posts, scoring 1 point for the opposition.'},
  {cat:'Rules', q:'How many interchange players is each team allowed on the bench?', opts:['3','4','5','6'], ans:1, explain:'Each AFL team has 4 interchange players on the bench who can rotate onto the field.'},
  {cat:'Rules', q:'What is "high contact" in AFL?', opts:['Contact above the knees','Contact to the head or neck area','Contact from behind','Sliding into a player'], ans:1, explain:'High contact refers to contact made to the head or neck of an opponent, which is heavily penalised in AFL.'},
  {cat:'Rules', q:'In AFL, what is a "deliberate out of bounds" infringement?', opts:['Kicking the ball deliberately out of bounds to slow the game','Running over the boundary line','Bouncing the ball near the boundary','Handballing over the boundary'], ans:0, explain:'Deliberate out of bounds is called when a player kicks or forces the ball deliberately over the boundary line to slow play.'},
  {cat:'Rules', q:'How many steps can an AFL player take before they must bounce or dispose of the ball?', opts:['10 steps','15 steps','No limit but must bounce regularly','As many as they want without bouncing'], ans:2, explain:'AFL players can take as many steps as they want, but must bounce or touch the ball to the ground every 15 metres.'},
  {cat:'Rules', q:'What does "prior opportunity" mean in AFL?', opts:['A player had the chance to dispose of the ball before being tackled','The first chance to kick in a game','A free kick given before the game','A mark taken before the siren'], ans:0, explain:'Prior opportunity means a player had the time and space to dispose of the ball before being tackled, relevant to holding the ball calls.'},
  {cat:'Rules', q:'What is the "50-metre penalty" in AFL?', opts:['A free kick moved 50m closer to goal','An automatic goal','A player is sent off','The opposition gets a free kick'], ans:0, explain:'A 50-metre penalty moves the free kick 50 metres closer to the goal, potentially giving the team a shot at goal.'},
  {cat:'Rules', q:'Can an AFL player kick the ball to themselves off a kickoff (kick-in)?', opts:['Yes, in any direction','No, never','Yes, but only backwards','Only if no opponent is nearby'], ans:0, explain:'A player taking a kick-in can kick the ball to themselves by kicking it and then running to catch it — this is legal.'},
  {cat:'Rules', q:'What happens when a player takes a "speccy" (spectacular mark)?', opts:['They receive 6 bonus points','They get a free kick from the mark','They take the mark where they caught it','The crowd goes wild but no special rule applies'], ans:1, explain:'A spectacular mark (speccy) is still just a mark — the player gets a free kick from the spot where the catch was taken.'},
  {cat:'Rules', q:'What is the "protected area" rule in AFL?', opts:['A zone around the goal square that cannot be entered','A zone that protects the player taking a free kick','An area only ruckmen can contest','The area around the centre circle'], ans:1, explain:'The protected area (or protected zone) prevents opponents from encroaching too closely on a player who has been awarded a free kick.'},
  {cat:'Rules', q:'How long is each AFL quarter (not including time on)?', opts:['15 minutes','20 minutes','25 minutes','30 minutes'], ans:1, explain:'Each AFL quarter is nominally 20 minutes of game time, but with time on added for stoppages, quarters typically last 25-35 minutes.'},
  {cat:'Rules', q:'What is a "free kick" awarded for shepherding in AFL?', opts:['Blocking an opponent more than 5 metres from the ball','Protecting a teammate with the ball','Pushing an opponent in the back','Running with the ball past an opponent'], ans:0, explain:'A free kick for illegal shepherding is awarded when a player blocks an opponent who is more than 5 metres from the ball.'},
  {cat:'Rules', q:'What is the "in the back" free kick in AFL?', opts:['Pushing an opponent in the back when they don\'t have the ball','Any contact from behind','Tackling from behind','Running into the back of an opponent'], ans:0, explain:'A free kick for "in the back" is awarded when a player pushes an opponent in the back when the opponent does not have the ball.'},
  {cat:'Rules', q:'What is a "throw in" in AFL?', opts:['When the ball is thrown back onto the field after going out of bounds','A handball that travels more than 10 metres','Throwing the ball instead of handpassing','When the umpire throws the ball up after a ball-up'], ans:0, explain:'When the ball goes out of bounds, an umpire performs a throw-in by throwing the ball back onto the ground at the boundary.'},
  {cat:'Rules', q:'Can a player handball the ball to themselves by throwing it in the air and catching it?', opts:['Yes','No — a handball must be received by a teammate','Only in special circumstances','Only in the final quarter'], ans:1, explain:'A handball must be struck with a clenched fist — you cannot throw it to yourself. It must be received by another player or clearly struck.'},
  {cat:'Rules', q:'What does "HTB" stand for in AFL statistics?', opts:['Hit To Backline','Holding The Ball','High To Body','Hit The Boundary'], ans:1, explain:'HTB stands for Holding The Ball, a common infringement in AFL where a player fails to dispose of the ball correctly when tackled.'},
  {cat:'Rules', q:'What is a "ball up" in AFL?', opts:['When the ball is kicked up high','When the umpire bounces the ball to restart play','When a mark is taken in a crowd','When the ball is stuck in a pack'], ans:1, explain:'A ball up occurs when the umpire bounces or throws up the ball to restart play after a stoppage.'},
  {cat:'Rules', q:'How many umpires typically officiate an AFL match?', opts:['2 field umpires','3 field umpires plus boundary and goal umpires','1 head umpire and 2 assistants','4 umpires total'], ans:1, explain:'AFL matches are officiated by 3 field umpires, plus boundary umpires and goal umpires.'},

  // ── TEAMS (25) ───────────────────────────────────────────────────
  {cat:'Teams', q:'Which team holds the record for the most AFL/VFL premierships?', opts:['Richmond','Essendon','Collingwood','Carlton'], ans:1, explain:'Essendon holds the record with 16 VFL/AFL premierships, the most of any club.'},
  {cat:'Teams', q:'Which AFL team is nicknamed "The Magpies"?', opts:['North Melbourne','Port Adelaide','Collingwood','St Kilda'], ans:2, explain:'Collingwood Football Club is nicknamed The Magpies, playing in black and white.'},
  {cat:'Teams', q:'Which AFL team plays their home games in Geelong?', opts:['Geelong Cats','Western Bulldogs','North Melbourne','Hawthorn'], ans:0, explain:'The Geelong Football Club plays at GMHBA Stadium in Geelong, Victoria.'},
  {cat:'Teams', q:'What colours do the Richmond Tigers wear?', opts:['Red and blue','Yellow and black','Blue and gold','Red and black'], ans:1, explain:'Richmond Tigers wear yellow and black — their famous "sash" design is iconic in AFL.'},
  {cat:'Teams', q:'Which team is nicknamed "The Hawks"?', opts:['Adelaide','Hawthorn','West Coast','Brisbane'], ans:1, explain:'Hawthorn Football Club is nicknamed The Hawks, playing in brown and gold.'},
  {cat:'Teams', q:'Port Adelaide\'s primary colours are what?', opts:['Red and blue','Teal and black','Black and white','Navy and silver'], ans:1, explain:'Port Adelaide Power wear teal (dark cyan) and black as their primary colours.'},
  {cat:'Teams', q:'Which club is nicknamed "The Saints"?', opts:['Melbourne','St Kilda','GWS Giants','Fremantle'], ans:1, explain:'St Kilda Football Club is nicknamed The Saints, playing in red, white and black.'},
  {cat:'Teams', q:'The Western Bulldogs were formerly known as what?', opts:['Footscray','Fitzroy','Box Hill','Williamstown'], ans:0, explain:'The Western Bulldogs were formerly known as Footscray Football Club before rebranding in 1996.'},
  {cat:'Teams', q:'Which team plays in "Prison Bar" jumpers?', opts:['Carlton','North Melbourne','Collingwood','Western Bulldogs'], ans:2, explain:'Collingwood\'s black and white vertical stripes are famously nicknamed "Prison Bars."'},
  {cat:'Teams', q:'What is the nickname of the Adelaide Crows?', opts:['The Crows','The Eagles','The Redlegs','The Power'], ans:0, explain:'Adelaide Football Club is officially nicknamed The Crows.'},
  {cat:'Teams', q:'Which team is known as "The Dockers"?', opts:['Fremantle','Port Adelaide','West Coast','Brisbane'], ans:0, explain:'The Fremantle Football Club is nicknamed The Dockers, referencing Fremantle\'s maritime history.'},
  {cat:'Teams', q:'North Melbourne\'s nickname is what?', opts:['The Blues','The Roos','The Bears','The Swans'], ans:1, explain:'North Melbourne Football Club is nicknamed The Roos (Kangaroos), playing in royal blue and white.'},
  {cat:'Teams', q:'Which AFL team is based in Alice Springs for some matches?', opts:['Adelaide Crows','GWS Giants','Gold Coast Suns','All three rotate'], ans:0, explain:'The Adelaide Crows regularly play "home" matches in Alice Springs as part of AFL\'s Indigenous community engagement.'},
  {cat:'Teams', q:'What do the initials GWS stand for?', opts:['Great Western Sydney','Greater Western Sydney','Grand Western Sydney','Greater West Sydney'], ans:1, explain:'GWS stands for Greater Western Sydney, representing the western suburbs of Sydney.'},
  {cat:'Teams', q:'Which two clubs share Marvel Stadium as their primary home ground?', opts:['Western Bulldogs and North Melbourne','Collingwood and Carlton','St Kilda and Melbourne','Western Bulldogs and St Kilda'], ans:3, explain:'The Western Bulldogs and St Kilda both use Marvel Stadium as their primary home ground.'},
  {cat:'Teams', q:'What colour is Essendon\'s traditional jumper?', opts:['Red with black sash','Black with red sash','Red and black halves','Blue and red'], ans:1, explain:'Essendon wear a black jumper with a red sash — one of the most iconic designs in AFL.'},
  {cat:'Teams', q:'The Brisbane Lions were formed from the merger of which two clubs?', opts:['Fitzroy and Brisbane Bears','South Melbourne and Brisbane Bears','Footscray and Brisbane Bears','Fitzroy and Gold Coast'], ans:0, explain:'The Brisbane Lions were formed when Fitzroy merged with the Brisbane Bears in 1996.'},
  {cat:'Teams', q:'Which team is nicknamed "The Power"?', opts:['Adelaide','West Coast','Port Adelaide','GWS'], ans:2, explain:'Port Adelaide Football Club is nicknamed The Power.'},
  {cat:'Teams', q:'Carlton Football Club is known by what nickname?', opts:['The Blues','The Navy','The Royals','The Dark Blues'], ans:0, explain:'Carlton Football Club is nicknamed The Blues, playing in navy blue.'},
  {cat:'Teams', q:'Which AFL team uses a seagull as part of their unofficial mascot culture?', opts:['Fremantle','West Coast','Melbourne','Sydney'], ans:0, explain:'Fremantle Dockers fans are sometimes called "Seagulls" though the official mascot relates to the Docker theme.'},
  {cat:'Teams', q:'Melbourne Football Club\'s colours are what?', opts:['Red and blue','Blue and red','Red, blue and white','Navy and scarlet'], ans:0, explain:'Melbourne Football Club wears red and blue, one of the oldest colour combinations in Australian football.'},
  {cat:'Teams', q:'Which team is known as "The Suns"?', opts:['West Coast','Gold Coast','Brisbane','Sydney'], ans:1, explain:'Gold Coast Football Club is nicknamed The Suns, reflecting the sunny Queensland climate.'},
  {cat:'Teams', q:'What is Hawthorn Football Club\'s home ground?', opts:['GMHBA Stadium','MCG','Marvel Stadium','University of Tasmania Stadium'], ans:1, explain:'Hawthorn primarily plays at the MCG, though they also play some games in Tasmania.'},
  {cat:'Teams', q:'Which club is nicknamed "The Giants"?', opts:['Melbourne','GWS','Collingwood','Hawthorn'], ans:1, explain:'GWS Giants are nicknamed The Giants, wearing orange and charcoal grey.'},
  {cat:'Teams', q:'Sydney Swans wear what colours?', opts:['Red and white','Blue and white','Red and blue','White and red'], ans:0, explain:'The Sydney Swans wear red and white, colours they adopted after moving from South Melbourne.'},
];

// Get questions for current month — same 15 for all players this month
function getMonthlyQuestions() {
  const now = new Date();
  const seed = now.getFullYear() * 100 + (now.getMonth() + 1);
  
  // Seeded shuffle — same result for everyone in the same month
  const shuffled = [...QUESTION_BANK];
  let s = seed;
  for (let i = shuffled.length - 1; i > 0; i--) {
    s = (s * 1664525 + 1013904223) & 0xffffffff;
    const j = Math.abs(s) % (i + 1);
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  
  // Pick 15 — ensure category spread (2-3 per category)
  const categories = {};
  const selected = [];
  
  for (const q of shuffled) {
    if (selected.length >= 15) break;
    const cat = q.cat;
    if (!categories[cat]) categories[cat] = 0;
    if (categories[cat] < 3) {
      selected.push(q);
      categories[cat]++;
    }
  }
  
  // Fill remaining if needed
  for (const q of shuffled) {
    if (selected.length >= 15) break;
    if (!selected.includes(q)) selected.push(q);
  }
  
  return selected.slice(0, 15);
}

module.exports = { QUESTION_BANK, getMonthlyQuestions };
